formatter: default
min-version: v0.12.0
rules:
  - description-empty
  - scope-enum
  - type-enum
settings:
  description-empty: {}
  scope-enum:
    argument:
      - ci
      - database
      - deps
      - docs
      - example
      - health
      - observability
      - release
      - rpc
      - service
      - tooling
    flags:
      allow-empty: true
  type-enum:
    argument:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
